run_mode: kSim
trigger_mode: kManual
init_motion_enable: true
planner_trigger_lead_time: 0.8
smooth_heading_enable: true
init_motion:
  z_takeoff: 2.5
  z_drop: 1.0
  x_forward: 2.0

# Group related parameters to be shared between nodes.
RobotDynamics:
  dt: 0.05
  v_max: 2.0
  v_homing_max: 1.5
  yaw_rate_max: 0.5
  v_init_max: 1.0
